### PR TITLE
Added harvest, height, and chl data 

### PR DESCRIPTION
**Pull request by readersm**
harvest still has weeds listed as their own record. I will add a new file for weeds over time and maybe we can add a season (summer vs. winter) column to be able to analyze the data that way over time. What do you think @Danielcalza

### CODE REVIEW

**Comment by Danielcalza** [comment]
Sounds great, I think adding a season column is great. I'll add it to the README too.

**Comment by readersm** [comment]
@Danielcalza Do you want to go ahead and look at these files to see if the column headings are consistent with what you have made changes to in the README.md file. go ahead and merge if they are correct, or let me know what to change!

**Comment by readersm** [comment]
Hey @Danielcalza I just had the chance to cross-reference this and the BD uploaded .csv files with the updated in the READ.ME file. These column headings are all consistent that I can see, though are we adding `Location` and `Samplingweek` to every csv file? Feel free to merge the above if not. Otherwise, I will add those columns. I'm working on data the last two hours of today so am free to do so.

Also, in the READ.ME, they are back ticks, not single quotes (Zack corrected me on this last time). I can go in and fix those.

**Comment by Danielcalza** [comment]
Hey @readersm I was only adding the `Samplingweek` at first to the plant height and then the biomass sampling files but the latter one is not as necessary if you agree. I did add the `Location` but again not as necessary if you agree. My argument for the location column was for the full break down of the `SiteName`.

I just noticed the backticks and can go back to fix them. Thank you! 

The column headings look right so I'll go ahead and merge. You can always add the changes after.

**Pull request merged**
